-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.7
-- Fri Jul 12 09:48:35 2024

-- parameterized module component declaration
component P3038DM_PLL
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : P3038DM_PLL
    port map (CLKI=>__, CLKOP=>__, LOCK=>__);
